In [1]:
import pandas as pd

In [2]:
historical_df = pd.read_csv('nba_updated_games.csv')

In [3]:
updated_df = pd.read_csv('updated_nba_boxscores.csv')

In [4]:
historical_df

,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,mp,mp.1,fg,fga,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,0,0.0,0.0,0.0,0.0,0,240.0,240.0,38.0,72.0,...,26.2,26.8,155.0,123.0,MIA,107,1,2023,2022-11-07,True
1,1,1.0,1.0,1.0,1.0,1,240.0,240.0,40.0,84.0,...,41.0,37.3,160.0,121.0,POR,110,0,2023,2022-11-07,False
2,2,2.0,2.0,2.0,2.0,2,240.0,240.0,41.0,78.0,...,28.6,41.1,250.0,125.0,DAL,90,1,2023,2022-12-14,True
3,3,3.0,3.0,3.0,3.0,3,240.0,240.0,29.0,74.0,...,12.6,33.0,183.0,110.0,CLE,105,0,2023,2022-12-14,False
4,4,4.0,4.0,4.0,4.0,4,240.0,240.0,39.0,81.0,...,22.8,29.0,178.0,111.0,DAL,95,1,2016,2015-12-09,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22079,22079,NaN,NaN,NaN,NaN,19,240.0,240.0,44.0,94.0,...,50.0,29.6,285.0,126.0,BOS,129,0,2024,2024-02-22,False
22080,22080,NaN,NaN,NaN,NaN,20,240.0,240.0,43.0,88.0,...,50.0,32.0,300.0,120.0,GSW,128,1,2024,2024-02-22,False
22081,22081,NaN,NaN,NaN,NaN,21,240.0,240.0,50.0,107.0,...,20.5,36.9,223.0,139.0,LAL,110,0,2024,2024-02-22,True
22082,22082,NaN,NaN,NaN,NaN,22,240.0,240.0,43.0,84.0,...,31.1,25.9,195.0,137.0,CLE,109,1,2024,2024-02-22,True
22083,22083,NaN,NaN,NaN,NaN,23,240.0,240.0,39.0,70.0,...,20.8,28.7,198.0,126.0,ORL,116,0,2024,2024-02-22,False

In [5]:
updated_df

,Unnamed: 0,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,0,240.0,240.0,34.0,80.0,0.425,8.0,27.0,0.296,21.0,...,23.3,34.1,156.0,109.0,PHI,104,1,2024,2024-02-23,False
1,1,240.0,240.0,40.0,90.0,0.444,12.0,29.0,0.414,12.0,...,27.3,26.6,148.0,118.0,CLE,97,0,2024,2024-02-23,True
2,2,240.0,240.0,46.0,81.0,0.568,15.0,35.0,0.429,9.0,...,42.0,40.9,160.0,147.0,NYK,102,1,2024,2024-02-24,True
3,3,240.0,240.0,37.0,82.0,0.451,13.0,38.0,0.342,15.0,...,25.0,37.3,278.0,135.0,BOS,116,0,2024,2024-02-24,False
4,4,240.0,240.0,50.0,102.0,0.490,15.0,39.0,0.385,8.0,...,22.4,39.2,158.0,128.0,ATL,121,1,2024,2024-02-23,True
5,5,240.0,240.0,46.0,106.0,0.434,12.0,39.0,0.308,17.0,...,33.3,25.8,139.0,124.0,TOR,123,0,2024,2024-02-23,False
6,6,240.0,240.0,38.0,82.0,0.463,13.0,29.0,0.448,17.0,...,18.8,32.2,150.0,113.0,NOP,95,1,2024,2024-02-23,True
7,7,240.0,240.0,39.0,104.0,0.375,7.0,32.0,0.219,10.0,...,29.4,33.7,241.0,109.0,MIA,106,0,2024,2024-02-23,False
8,8,240.0,240.0,43.0,87.0,0.494,12.0,24.0,0.500,14.0,...,42.9,34.4,168.0,130.0,DET,109,1,2024,2024-02-24,True
9,9,240.0,240.0,43.0,85.0,0.506,14.0,31.0,0.452,9.0,...,30.0,32.5,174.0,126.0,ORL,112,0,2024,2024-02-24,False
10,10,240.0,240.0,42.0,96.0,0.438,15.0,38.0,0.395,19.0,...,29.4,30.3,168.0,126.0,LAL,123,1,2024,2024-02-23,False
11,11,240.0,240.0,49.0,95.0,0.516,11.0,27.0,0.407,14.0,...,33.3,29.5,157.0,129.0,SAS,118,0,2024,2024-02-23,True
12,12,240.0,240.0,50.0,85.0,0.588,13.0,33.0,0.394,14.0,...,30.0,38.4,200.0,141.0,POR,112,1,2024,2024-02-23,True
13,13,240.0,240.0,46.0,101.0,0.455,8.0,25.0,0.320,12.0,...,33.8,34.8,200.0,127.0,DEN,127,0,2024,2024-02-23,False
14,14,240.0,240.0,35.0,104.0,0.337,6.0,35.0,0.171,10.0,...,38.1,33.4,146.0,100.0,MIN,101,1,2024,2024-02-24,False
15,15,240.0,240.0,36.0,84.0,0.429,12.0,38.0,0.316,17.0,...,33.3,25.8,111.0,109.0,BRK,86,0,2024,2024-02-24,True
16,16,240.0,240.0,41.0,104.0,0.394,9.0,38.0,0.237,15.0,...,100.0,32.0,163.0,108.0,OKC,147,1,2024,2024-02-23,False
17,17,240.0,240.0,55.0,92.0,0.598,20.0,40.0,0.500,17.0,...,60.0,40.6,130.0,143.0,WAS,106,0,2024,2024-02-23,True
18,18,240.0,240.0,41.0,87.0,0.471,13.0,37.0,0.351,17.0,...,42.9,35.5,163.0,125.0,MIN,107,1,2024,2024-02-23,True
19,19,240.0,240.0,43.0,98.0,0.439,13.0,35.0,0.371,8.0,...,50.0,32.4,176.0,118.0,MIL,112,0,2024,2024-02-23,False
20,20,240.0,240.0,38.0,95.0,0.400,7.0,31.0,0.226,27.0,...,30.1,32.9,142.0,115.0,HOU,114,1,2024,2024-02-23,False
21,21,240.0,240.0,37.0,93.0,0.398,15.0,45.0,0.333,25.0,...,50.0,32.8,154.0,120.0,PHO,110,0,2024,2024-02-23,True
22,22,240.0,240.0,37.0,84.0,0.440,12.0,32.0,0.375,15.0,...,40.0,40.7,168.0,118.0,MEM,95,1,2024,2024-02-23,True
23,23,240.0,240.0,38.0,91.0,0.418,8.0,35.0,0.229,11.0,...,28.7,34.3,231.0,106.0,LAC,101,0,2024,2024-02-23,False
24,24,240.0,240.0,32.0,88.0,0.364,11.0,39.0,0.282,9.0,...,50.0,32.5,134.0,99.0,GSW,97,1,2024,2024-02-23,False
25,25,240.0,240.0,38.0,89.0,0.427,13.0,42.0,0.310,8.0,...,35.3,29.7,105.0,112.0,CHO,84,0,2024,2024-02-23,True

In [6]:
nba_updated_games = pd.concat([historical_df, updated_df], ignore_index=True)

In [7]:
nba_updated_games

,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,mp,mp.1,fg,fga,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,0.0,0.0,0.0,0.0,0.0,0,240.0,240.0,38.0,72.0,...,26.2,26.8,155.0,123.0,MIA,107,1,2023,2022-11-07,True
1,1.0,1.0,1.0,1.0,1.0,1,240.0,240.0,40.0,84.0,...,41.0,37.3,160.0,121.0,POR,110,0,2023,2022-11-07,False
2,2.0,2.0,2.0,2.0,2.0,2,240.0,240.0,41.0,78.0,...,28.6,41.1,250.0,125.0,DAL,90,1,2023,2022-12-14,True
3,3.0,3.0,3.0,3.0,3.0,3,240.0,240.0,29.0,74.0,...,12.6,33.0,183.0,110.0,CLE,105,0,2023,2022-12-14,False
4,4.0,4.0,4.0,4.0,4.0,4,240.0,240.0,39.0,81.0,...,22.8,29.0,178.0,111.0,DAL,95,1,2016,2015-12-09,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22105,NaN,NaN,NaN,NaN,NaN,21,240.0,240.0,37.0,93.0,...,50.0,32.8,154.0,120.0,PHO,110,0,2024,2024-02-23,True
22106,NaN,NaN,NaN,NaN,NaN,22,240.0,240.0,37.0,84.0,...,40.0,40.7,168.0,118.0,MEM,95,1,2024,2024-02-23,True
22107,NaN,NaN,NaN,NaN,NaN,23,240.0,240.0,38.0,91.0,...,28.7,34.3,231.0,106.0,LAC,101,0,2024,2024-02-23,False
22108,NaN,NaN,NaN,NaN,NaN,24,240.0,240.0,32.0,88.0,...,50.0,32.5,134.0,99.0,GSW,97,1,2024,2024-02-23,False
22109,NaN,NaN,NaN,NaN,NaN,25,240.0,240.0,38.0,89.0,...,35.3,29.7,105.0,112.0,CHO,84,0,2024,2024-02-23,True

In [8]:
nba_updated_games.to_csv('nba_updated_games.csv')