In [1]:
import pandas as pd

In [2]:
historical_df = pd.read_csv('nba_updated_games.csv')

In [3]:
updated_df = pd.read_csv('updated_nba_boxscores.csv')

In [4]:
historical_df

,Unnamed: 0,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,0,240.0,240.0,38.0,72.0,0.528,16.0,37.0,0.432,18.0,...,26.2,26.8,155.0,123.0,MIA,107,1,2023,2022-11-07,True
1,1,240.0,240.0,40.0,84.0,0.476,14.0,39.0,0.359,13.0,...,41.0,37.3,160.0,121.0,POR,110,0,2023,2022-11-07,False
2,2,240.0,240.0,41.0,78.0,0.526,8.0,24.0,0.333,15.0,...,28.6,41.1,250.0,125.0,DAL,90,1,2023,2022-12-14,True
3,3,240.0,240.0,29.0,74.0,0.392,13.0,38.0,0.342,19.0,...,12.6,33.0,183.0,110.0,CLE,105,0,2023,2022-12-14,False
4,4,240.0,240.0,39.0,81.0,0.481,6.0,20.0,0.300,14.0,...,22.8,29.0,178.0,111.0,DAL,95,1,2016,2015-12-09,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21701,21701,240.0,240.0,43.0,92.0,0.467,12.0,34.0,0.353,12.0,...,51.5,33.0,200.0,112.0,MIN,117,0,2024,2023-11-10,False
21702,21702,240.0,240.0,41.0,85.0,0.482,9.0,26.0,0.346,26.0,...,27.7,27.1,150.0,126.0,MIA,106,1,2020,2020-09-19,True
21703,21703,240.0,240.0,33.0,85.0,0.388,12.0,44.0,0.273,28.0,...,51.5,36.2,141.0,114.0,BOS,117,0,2020,2020-09-19,False
21704,21704,240.0,240.0,42.0,82.0,0.512,12.0,27.0,0.444,12.0,...,53.2,28.0,146.0,126.0,TOR,121,1,2024,2023-11-24,False
21705,21705,240.0,240.0,44.0,83.0,0.530,13.0,39.0,0.333,20.0,...,25.0,34.3,195.0,136.0,CHI,108,0,2024,2023-11-24,True

In [5]:
updated_df

,Unnamed: 0,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,0,240.0,240.0,43.0,80.0,0.538,11.0,30.0,0.367,23.0,...,50.0,33.1,163.0,127.0,DAL,115,1,2024,2024-01-27,True
1,1,240.0,240.0,43.0,98.0,0.439,16.0,46.0,0.348,13.0,...,100.0,35.7,165.0,121.0,SAC,120,0,2024,2024-01-27,False
2,2,240.0,240.0,42.0,88.0,0.477,10.0,33.0,0.303,13.0,...,50.0,38.6,156.0,117.0,NOP,83,1,2024,2024-01-26,True
3,3,240.0,240.0,32.0,82.0,0.390,9.0,36.0,0.250,10.0,...,45.0,41.9,127.0,96.0,OKC,107,0,2024,2024-01-26,False
4,4,240.0,240.0,52.0,93.0,0.559,17.0,32.0,0.531,10.0,...,30.0,30.9,230.0,140.0,IND,109,1,2024,2024-02-08,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
281,281,240.0,240.0,42.0,90.0,0.467,15.0,41.0,0.366,8.0,...,23.5,37.3,179.0,122.0,ORL,106,0,2024,2024-01-26,True
282,282,240.0,240.0,48.0,95.0,0.505,9.0,32.0,0.281,22.0,...,50.0,53.1,214.0,134.0,TOR,107,1,2024,2024-01-26,True
283,283,240.0,240.0,44.0,96.0,0.458,6.0,32.0,0.188,13.0,...,33.3,29.5,209.0,116.0,LAC,127,0,2024,2024-01-26,False
284,284,240.0,240.0,45.0,81.0,0.556,16.0,31.0,0.516,15.0,...,25.0,40.5,181.0,134.0,CLE,128,1,2024,2024-01-31,False
285,285,240.0,240.0,47.0,89.0,0.528,12.0,35.0,0.343,22.0,...,40.0,26.5,196.0,142.0,DET,121,0,2024,2024-01-31,True

In [7]:
nba_updated_games = pd.concat([historical_df, updated_df], ignore_index=True)

In [10]:
nba_updated_games.to_csv('nba_updated_games.csv')