In [47]:
import pandas as pd
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.impute import KNNImputer

In [48]:
df_updated = pd.read_csv('df_combined.csv')

/var/folders/mv/f4c9n99j583b7mz1mbs2815h0000gn/T/ipykernel_21152/203918621.py:1: DtypeWarning: Columns (142) have mixed types. Specify dtype option on import or set low_memory=False.
  df_updated = pd.read_csv('df_combined.csv')

In [49]:
df_updated_sample = df_updated[18252:19287]

In [50]:
df_updated_sample

,Unnamed: 0,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,...,blk%_max_opp_10,tov%_max_opp_10,usg%_max_opp_10,ortg_max_opp_10,drtg_max_opp_10,total_opp_10,home_opp_10,home_next,team_opp_next,date_next
18252,18252,0.0,0.0,0.478261,0.235294,0.645933,0.620690,0.500000,0.577197,0.604651,...,0.1283,0.340147,0.158205,0.525592,0.537647,0.514286,0.6,1.0,POR,2023-11-14
18253,18253,0.0,0.0,0.456522,0.382353,0.468900,0.275862,0.363636,0.339667,0.395349,...,0.0915,0.247589,0.259231,0.460190,0.517647,0.443750,0.5,0.0,CHI,2023-11-12
18254,18254,0.0,0.0,0.391304,0.441176,0.339713,0.448276,0.515152,0.406176,0.511628,...,0.0690,0.311845,0.203077,0.389100,0.557647,0.418750,0.7,1.0,MIN,2023-11-12
18255,18255,0.0,0.0,0.413043,0.411765,0.389952,0.379310,0.424242,0.408551,0.465116,...,0.0958,0.256289,0.255128,0.470142,0.524706,0.458036,0.5,1.0,ATL,2023-11-14
18256,18256,0.0,0.0,0.434783,0.426471,0.404306,0.413793,0.409091,0.459620,0.627907,...,0.1324,0.323166,0.170897,0.489573,0.496471,0.413393,0.6,0.0,CHO,2023-11-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19282,19282,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,POR,2024-01-26
19283,19283,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,SAC,2024-01-25
19284,19284,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,BKN,2024-01-25
19285,19285,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,ORL,2024-01-26
19286,19286,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,HOU,2024-01-26

In [56]:
# iterative imputation with randomforest regressor (too computationally intensive, working out best sample sizes for imputation)

# separate the DataFrame into numerical and categorical parts
df_numerical = df_updated_sample.select_dtypes(include=['int64', 'float64'])
df_categorical = df_updated_sample.select_dtypes(exclude=['int64', 'float64'])

# qdjusted RandomForestRegressor within IterativeImputer
regressor = RandomForestRegressor(
    n_estimators=120,  # slightly more trees
    max_depth=None,    # no limit on the depth
    min_samples_leaf=2,  # more generalization
    max_features='sqrt',  # default
    random_state=0,    # dor reproducibility
    n_jobs=-1          # use all available CPUs
)

# Initialize the IterativeImputer with RandomForestRegressor
imputer = IterativeImputer(estimator=regressor, max_iter=10, random_state=0)

# Fit the imputer and transform the numerical DataFrame
df_numerical_imputed = imputer.fit_transform(df_numerical)

In [57]:
df_numerical_imputed

array([[1.82520000e+04, 0.00000000e+00, 0.00000000e+00, ...,
        5.14285714e-01, 6.00000000e-01, 1.00000000e+00],
       [1.82530000e+04, 0.00000000e+00, 0.00000000e+00, ...,
        4.43750000e-01, 5.00000000e-01, 0.00000000e+00],
       [1.82540000e+04, 0.00000000e+00, 0.00000000e+00, ...,
        4.18750000e-01, 7.00000000e-01, 1.00000000e+00],
       ...,
       [1.92840000e+04, 0.00000000e+00, 0.00000000e+00, ...,
        4.60029281e-01, 5.01805556e-01, 0.00000000e+00],
       [1.92850000e+04, 0.00000000e+00, 0.00000000e+00, ...,
        4.60141260e-01, 5.04583333e-01, 1.00000000e+00],
       [1.92860000e+04, 0.00000000e+00, 0.00000000e+00, ...,
        4.60141260e-01, 5.04583333e-01, 1.00000000e+00]])

In [65]:
df_numerical_imputed = pd.DataFrame(df_numerical_imputed, columns=df_numerical.columns)

In [66]:
# recombine the DataFrame

df_updated_imputed = pd.concat([df_numerical_imputed, df_categorical], axis=1)

In [67]:
df_updated_imputed

,Unnamed: 0,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,...,drtg_max_opp_10,total_opp_10,home_opp_10,home_next,team,team_opp,date,won,team_opp_next,date_next
0,18252.0,0.0,0.0,0.478261,0.235294,0.645933,0.620690,0.500000,0.577197,0.604651,...,0.537647,0.514286,0.6,1.0,NaN,NaN,NaN,NaN,NaN,NaN
1,18253.0,0.0,0.0,0.456522,0.382353,0.468900,0.275862,0.363636,0.339667,0.395349,...,0.517647,0.443750,0.5,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2,18254.0,0.0,0.0,0.391304,0.441176,0.339713,0.448276,0.515152,0.406176,0.511628,...,0.557647,0.418750,0.7,1.0,NaN,NaN,NaN,NaN,NaN,NaN
3,18255.0,0.0,0.0,0.413043,0.411765,0.389952,0.379310,0.424242,0.408551,0.465116,...,0.524706,0.458036,0.5,1.0,NaN,NaN,NaN,NaN,NaN,NaN
4,18256.0,0.0,0.0,0.434783,0.426471,0.404306,0.413793,0.409091,0.459620,0.627907,...,0.496471,0.413393,0.6,0.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19282,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,SAS,OKC,2024-01-24,NaN,POR,2024-01-26
19283,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,GSW,ATL,2024-01-24,NaN,SAC,2024-01-25
19284,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,MIN,WAS,2024-01-24,NaN,BKN,2024-01-25
19285,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,MEM,MIA,2024-01-24,NaN,ORL,2024-01-26
19286,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,CHA,DET,2024-01-24,NaN,HOU,2024-01-26